### ISSUE TITLE
더미 포스트 작성

### ISSUE THREAD

**Issue by kjkandrea** [soozo/Divi-child#3]
포스트 레이아웃을 잡기위한 준비과정입니다.
구텐베르크 에디터를 이용하여 사이트내에 더미포스트를 작성하여주세요.

**기본스펙**
헤드라인이 3deps까지 작성되어야 합니다. (h1, h2, h3)
한글 더미텍스트로 작성된 패러그래프가 포함되어야합니다.

**Comment by soozo** [comment]
중간 보고 드립니다.
http://wireframe.kr/dummy/

**Comment by soozo** [comment]
http://wireframe.kr/dummy/ 완료. 이슈 종료합니다 :)
