### ISSUE TITLE
sj 커스텀 스크립트 추가

### ISSUE THREAD

**Issue by kjkandrea** [soozo/Divi-child#5]
assets/js 폴더내에 전용 커스텀 스크립트 파일을 생성하여주세요.
해당파일안에 console log를 출력하는 구문을 넣어 콘솔창안에 임의의 텍스트가 출력되게 해야합니다.
진행하면서 아래의 항목을 체크하여주세요.

**필요조건**

- [x] assets/js 폴더내에 .js 파일을 생성
- [x] .js 파일내에 console log 구문작성
- [x] function.php 내에서 js파일을 인큐
- [x] 콘솔창에 입력한 로그가 출력되는지 확인

**Comment by soozo** [comment]
확인했습니다.

**Comment by soozo** [comment]
https://github.com/soozo/Divi-child/commit/51b935b8daf91be7be09b19d5cc2867f41d1e521 완료. 이슈 종료합니다.
